---
- name: Windows - Promote to DC
  hosts: windows
  gather_facts: false
  tasks:
    - name: Wait for connection
      wait_for_connection:
    - name: Gather facts
      setup:
    - name: Promote to DC
      include_role:
        name: win-promote-to-dc